In [1]:
import numpy as np


In [6]:
arr = np.random.randint(1,100,size = (3,5))
print(arr)

[[59 78 20  2 25]
 [ 6 74  2  9 59]
 [17 40 60 68  8]]


In [7]:
arr_2 = arr.reshape(5,3)
print(arr_2)

[[59 78 20]
 [ 2 25  6]
 [74  2  9]
 [59 17 40]
 [60 68  8]]


In [8]:
flat_as_row = arr_2.flatten() #row wise flat
print(flat_as_row)

[59 78 20  2 25  6 74  2  9 59 17 40 60 68  8]


In [11]:
flat_as_col = np.ravel(arr_2,order = 'F') #column wise flat
print(flat_as_col)

[59  2 74 59 60 78 25  2 17 68 20  6  9 40  8]


In [13]:
a = np.random.randint(1,10,size=(2,4))
b = np.random.randint(10,20,size=(2,4))
print(a)
print(b)

[[7 7 8 4]
 [4 3 1 5]]
[[15 13 15 16]
 [11 12 12 15]]


In [14]:
con_row = np.concatenate((a,b),axis = 0)
print(con_row)

[[ 7  7  8  4]
 [ 4  3  1  5]
 [15 13 15 16]
 [11 12 12 15]]


In [15]:
con_col = np.concatenate((a,b),axis = 1)
print(con_col)

[[ 7  7  8  4 15 13 15 16]
 [ 4  3  1  5 11 12 12 15]]


In [17]:
mat = np.random.randint(1,10, size = (3,3))
print(mat)
t = mat.T
print(t)

[[3 4 2]
 [1 1 2]
 [1 6 7]]
[[3 1 1]
 [4 1 6]
 [2 2 7]]


In [18]:
#array split
a = np.random.randint(1,10,size = (10,))
print(a)
b = np.array_split(a,3)
print(b)

[5 3 9 9 9 5 3 2 8 4]
[array([5, 3, 9, 9]), array([9, 5, 3]), array([2, 8, 4])]


In [19]:
#for equal division, so that each slice get the same number of entries
a = np.random.randint(1,10,size = (10,))
b = np.split(a,3) #its not possible, as we can't divide 10 equally for 3 slice
#so it will show error
print(b)

ValueError: array split does not result in an equal division

In [20]:
#for equal division, so that each slice get the same number of entries
a = np.random.randint(1,10,size = (9,))
b = np.split(a,3) #its not possible, as we can't divide 10 equally for 3 slice
#so it will show error
print(b)

[array([4, 5, 1]), array([3, 5, 8]), array([8, 4, 1])]


In [22]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4 ,5 ])
add = x + y
sub = x-y
mul = x*y
div = x/y
print(add)
print(sub)
print(mul)
print(div)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]


#mathematics and trigonometry

In [26]:
x = np.array([10,20,30,40,45,90])
sin_x = np.sin(x) #converts from radian not from degree
print(sin_x)
cos_x = np.cos(x)
print(cos_x)
tan_x = np.tan(x)
print(tan_x)

[-0.54402111  0.91294525 -0.98803162  0.74511316  0.85090352  0.89399666]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.52532199 -0.44807362]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493  1.61977519 -1.99520041]


#Degree to Radian Conversion

In [27]:
deg = np.array([10,20,30,40,50])
rad = np.deg2rad(deg)
print(rad)

[0.17453293 0.34906585 0.52359878 0.6981317  0.87266463]


In [29]:
deg = np.rad2deg(rad)
print(deg)

[10. 20. 30. 40. 50.]


In [30]:
x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log = np.log10(x)
base_2_log = np.log2(x)
print(base_10_log)
print(base_2_log)


[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]


In [32]:
x = np.array([ 10 , 8 , 16 , 100 ])
sums = np.sum(x)
cum_sums = np.cumsum(x)
print(sums)
print(cum_sums)

134
[ 10  18  34 134]


#Logical Function

In [35]:
x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16 ,5 ])
greater_than = x>y
print(greater_than)
less_than = x<y
print(less_than)
equals = (x==y)
print(equals)

[ True  True False  True]
[False False False False]
[False False  True False]


In [36]:
print(np.all(greater_than))

False


In [38]:
x = np.array([ 10 , 8 , 16 , 100 ])
print(x)
y = x.copy()
print(y)
y.sort()
print(y)

[ 10   8  16 100]
[ 10   8  16 100]
[  8  10  16 100]


In [40]:
mat = np.array([[10,3,5],[8,4,9]])
hor_sort = np.sort(mat,axis = 1)
ver_sort = np.sort(mat,axis = 0)
print(mat)
print(hor_sort)
print(ver_sort)


[[10  3  5]
 [ 8  4  9]]
[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [41]:
print(x)

[ 10   8  16 100]


In [42]:
index = np.where(x==16)
print(index)

(array([2]),)


In [45]:
x = np.array(
    [[10,20,40],
    [19,34,56]]
)
print(x)
ind = np.where(x == 34)
print(ind)

[[10 20 40]
 [19 34 56]]
(array([1]), array([1]))


In [46]:
index = np.where(x>15)
print(index)

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))


In [47]:
x = np.array([ 10,100 , 8 , 16 , 100 ])
max_val_ind = np.argmax(x)
min_val_ind = np.argmin(x)
print(max_val_ind)
print(min_val_ind)

1
2


#value count in ndarray

In [48]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[80 62 47 59 70 42 33 61 98 86 99 32 43 70 74 89 25 39 79 81 32 77 53 88
 33 51 94 22 91 58 58 74 20 63 50 93 75 66 13 51 55 21 84 63 71 70 94 55
 92 56 80 73 22 63  1  3 80 47 73 71 71 76 98 50 40 97 71 70 71 83 36 40
 68 88 57 45 49 21  9 63 98 63 51 76 93 88 13 38 23 36  2 67 33 63 41  4
 88 48 69 22]


In [52]:
val_greater_than_50 = np.count_nonzero(a>50)
print(val_greater_than_50)

64


In [54]:
unique_val,count = np.unique(a,return_counts = True)
print(unique_val)
print(count)

[ 1  2  3  4  9 13 20 21 22 23 25 32 33 36 38 39 40 41 42 43 45 47 48 49
 50 51 53 55 56 57 58 59 61 62 63 66 67 68 69 70 71 73 74 75 76 77 79 80
 81 83 84 86 88 89 91 92 93 94 97 98 99]
[1 1 1 1 1 2 1 2 3 1 1 2 3 2 1 1 2 1 1 1 1 2 1 1 2 3 1 2 1 1 2 1 1 1 6 1 1
 1 1 4 5 2 2 1 2 1 1 3 1 1 1 1 4 1 1 1 2 2 1 3 1]
