In [1]:
import numpy as np

**NUMPY** uses *SIMD (Single Instruction Multiple Data)* method. As, list uses single instruction one by one, it is slow and not efficient. \n
On the other hand numpy uses parallel computation method. That's why it is must faster.

In [2]:
arr = [1,2,3]
print(arr*5)
arr2 = [x*5 for x in arr]
print(arr2)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
arr1 = np.array([1,2,3])
arr2 = arr1 * 5
print(arr2)

[ 5 10 15]


**Dimension of array or matrix**

In [4]:
#Nd array (N dimensional array)

#1D array

arr1 = np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.ndim)

<class 'numpy.ndarray'>
1


In [5]:
#2D array
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [6]:
#3D array
arr3 = np.array([
    [[1,2,3],
    [4,5,6]],
    [[1,2,3],
     [3,4,5]],

    [[1,2,3],
     [3,4,5]]

])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]
3


Array **Attributes**

In [7]:
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#datatype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

(6,)
(2, 3)
(3, 2, 3)
int64
int64
int64


***Up-Casting:*** upcasting is the process where elements are automatically converted to a data type with a higher level of precision or a more general scope to avoid data loss

In [8]:
arr4 = np.array([2.4,6.4])
print(arr4.dtype)

float64


In [9]:
arr5 = np.array([1,3,5,6.5])
print(arr5.dtype)

float64


In [10]:
arr6 = np.array([1,3,5,6.5,'a'])
print(arr6.dtype)

<U32


Selecting a Data Type for an array

In [11]:
arr = np.array([1,3,4],dtype = np.int8)
print(arr.dtype)

int8


In [12]:
arr7 = np.array([1,True,3.4,"helo"])
print(arr7.dtype)

<U32


Array creation from **existing data**

In [13]:
#list
lst = [10,20,30,40,40.8]
arr = np.array(lst,dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32


In [14]:
lst = [10, True, "Hello", 10]
arr = np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

['10' 'True' 'Hello' '10']
<class 'numpy.ndarray'>
<U21


In [15]:
lst = [10, True, "Hello", [10,30,45]]
arr = np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
matrix = [
    [1,3,4],
    [23,4,3]
]
mat = np.array(matrix)
print(mat)
print(type(mat))

In [ ]:
#convert from tuple
tup = (10,20,30,40)
arr = np.array(tup)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)

In [ ]:
#set
st = {1,2,3}
arr = np.array(list(st))
print(type(arr))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:
#dictionary
dic = {'a' : 10,
       'b' : 20,
       'c' : 30}
keys = dic.keys()
values = dic.values()
items = dic.items()
key_ar = np.array(list(keys))
print(key_ar)
val_arr = np.array(list(items))
print(val_arr)
items_arr = np.array(list(items))
print(items_arr)
print(items_arr.ndim)
print(items_arr.shape)
print(items_arr.size)

Array generation with ***random*** values

In [ ]:
arr = np.random.rand(2,3) # 2 rows and 3 column
print(arr)

In [ ]:
#random integer
arr2 = np.random.randint(1,110,(5,4)) # first 2 ta value mean kore, koto theke koto porjonto chacchi, ar baki 2 ta orientation
print(arr2)

For Float

In [ ]:
arr2 = np.random.uniform(75,110,(5,4)) # first 2 ta value mean kore, koto theke koto porjonto chacchi, ar baki 2 ta orientation
print(arr2)

In [ ]:
#array creation with range
#np.arange(first,end,step) (reality-> end-1)
arr = np.arange(1,10,1).reshape(3,3)

In [ ]:
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr.ndim)

In [ ]:
#np.linspace(starting,end(included), num of point)
arr = np.linspace(1,10,8)

In [ ]:
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr.ndim)

In [ ]:
#np.logspace(star,end(included),how much value)
arr = np.logspace(0,4,5)


In [ ]:
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr.ndim)

In [16]:
arr = np.logspace(0,4,5,base = 2)
print(arr)

[ 1.  2.  4.  8. 16.]


Indexing and Slicing

In [17]:
print(arr1)

[1 2 3 4 5 6]


In [18]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [21]:
print(arr1[2])

3


In [22]:
arr1[2] = 100

In [23]:
print(arr1)

[  1   2 100   4   5   6]


In [24]:
print(arr2[1][1])

5


In [25]:
#slicing
print(arr1[0:4])

[  1   2 100   4]


In [26]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [33]:
#2D slicing
#arr[row_start:row_end:step,col_start:col_end:col_step]

print(arr2[0:1, ]) #row0
print(arr2[1,]) #row1
print(arr2[0:2,0:1]) #column1
print(arr2[0:2,1:2]) #column2
print(arr2[::,0:2]) #spcific portion

[[1 2 3]]
[4 5 6]
[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


Advance indexing of Numpy

In [37]:
#view mode
arr1 = np.array([1,2,3,4,5,6,7])
arr_one = arr1[0:4]
print(arr_one)
arr_one[2] = 100
print(arr_one)
print(arr1)

[1 2 3 4]
[  1   2 100   4]
[  1   2 100   4   5   6   7]


In [39]:
#copy mode
arr1 = np.array([1,2,3,4,5,6,7])
arr_one = arr1[0:4].copy()
print(arr_one)
arr_one[2] = 100
print(arr_one)
print(arr1)

[1 2 3 4]
[  1   2 100   4]
[1 2 3 4 5 6 7]


In [42]:
arr1 = np.array([1,2,3,4,5,6,7])
values = arr1[[2,3,5]]
print(values)

[3 4 6]


In [43]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [44]:
print(arr2[[0,1],[1,2]])

[2 6]


By using boolean function

In [45]:
print(arr2[arr2>2])

[3 4 5 6]


In [46]:
print(arr2[arr2<2])

[1]


In [47]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [49]:
#iteration
for i in arr2:
  for j in i:
    print(j)


1
2
3
4
5
6


In [51]:
for i in np.nditer(arr2):
  print(i)

1
2
3
4
5
6


In [53]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]


In [52]:
for i in np.nditer(arr3):
  print(i)

1
2
3
4
5
6
1
2
3
3
4
5
1
2
3
3
4
5


In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1. You have a list of temperatures recorded in Celsius. Your task is to:
Create a NumPy array from the given list.
Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
Print the new Fahrenheit array.


In [58]:
temp = [10, 45, 54, 100, 36, 4, 0]
arr = np.array(temp)
faren_arr = arr* 1.8 +32
print(faren_arr)

[ 50.  113.  129.2 212.   96.8  39.2  32. ]


You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes


In [61]:
lap_times = [62.5, 64.2, 30, 65.1, 66.4, 62.9, 61.7, 63.5, 64.0, 60.8]
arr = np.array(lap_times)
print(arr.shape)
print(arr.size)
print(arr.dtype)
min_arr = arr/60
print(min_arr)

(10,)
10
float64
[1.04166667 1.07       0.5        1.085      1.10666667 1.04833333
 1.02833333 1.05833333 1.06666667 1.01333333]
